### PR TITLE
Update migrateAccount.py to create folders properly

### PR DESCRIPTION
**Pull request by slibby**
I noticed an error in folder creation when moving from IWA accounts to SAML accounts - see what you think of this.

### CODE REVIEW

**Comment by ecaldwell** [comment]
Was this in Portal? When I test with the existing script, it (Portal/ArcGIS Online) automatically creates a folder of the pattern `<source username>_<folder name>`. In your usage, it failed on the folder creation step?

**Comment by slibby** [comment]
Yes, it was in Portal. a user was using on their infrastructure and they said they though that having a new folder created with "username_foldername" was unexpected and not ideal. This preserves folder naming, since what they're trying to do is migrate every IWA user to a SAML user and then have them login and have their stuff look the same (not have strange username-based folders).

Does that make sense? I think it is a more common use case, though I can see if you were migrating one user to another user, you would want to know what content came from that user. Maybe we could add a "preserve-folder-names" flag or something to the script?

**Comment by ecaldwell** [comment]
It does make sense. I don't disagree with your user's example, but at the same time it could introduce some new problems. For example, when migrating content from a built-in account to an enterprise account I would want folder names preserved because both accounts are really one physical person. 

However, if I have an established account with my own folders and content and somebody leaves my organization we might choose to migrate all of their content into my account. Now it might be very difficult/cumbersome to determine which content came from them if it just automatically dumps it into my existing folder structure. I suppose in this case simply adding a tag with their username to each item would let me easily find/differentiate it.

I think your suggestion of a flag (command line parameter) makes the most sense. Also, I noticed that it blindly copies all folders even if they don't have any content in them. Suggest you add a check to ensure the folder has content with a test like `len(folderContent['items']) > 0` before creating the folder in the destination account.

**Comment by slibby** [comment]
What ye think of that?

**Comment by ecaldwell** [comment]
There are two different references to `folder['title']` on line 229 and I think the `createFolder` method on line 232 is using the title of the last folder in the destination account. Setting the first reference to a variable instead like `folderTitle` and then using that in the `createFolder` method should resolve it.

**Comment by slibby** [comment]
updated the variable names in the Line 229 list comprehension so they are different from the old Folders -- I don't think defining a variable earlier makes much of a difference  -- dict lookup vs. variable recall should be just as fast in this use case.

Testing it on mine.

**Comment by slibby** [comment]
took a bit more finagling but working now.

**Comment by ecaldwell** [comment]
So close...everything is working great on my end with one exception. It's still creating empty folders. I think your test on line 228 can be changed to `if len(folder['items']) == 0:` to correct that. Could you also change your double quotes to single for consistency?

**Comment by ecaldwell** [comment]
I was wrong. I'm getting `KeyError: 'items'` now. I think you may have to call `getUserContent` with the folder to determine if it is empty or not.

**Comment by slibby** [comment]
ok, I think that addresses it?

**Comment by ecaldwell** [comment]
Solid. Nice work!

**Pull request merged**
